var UIModule=function(){function m(d){13==d.keyCode&&(0==gameModule.isRunning()?(document.getElementById("status").innerHTML="Game is running",document.getElementById("started").innerHTML="Press enter to pause",document.getElementById("Restart").innerHTML="Restart",gameModule.run()):(document.getElementById("status").innerHTML="Game is paused",document.getElementById("started").innerHTML="Press enter to resume",gameModule.pause()))}function g(d){var g,m=gameModule.getCanvas().getBoundingClientRect();
g=d.clientX-m.left;d=d.clientY-m.top;g=parseInt(g/gameModule.getCellDiameter());d=parseInt(d/gameModule.getCellDiameter());gameModule.drawCell(g,d)}return{initialize:function(){window.addEventListener("keydown",m,!1);document.getElementById("Acorn").addEventListener("mousedown",gameModule.makeAcorn,!1);document.getElementById("Walker").addEventListener("mousedown",gameModule.makeWalker,!1);document.getElementById("Gun").addEventListener("mousedown",gameModule.makeGun,!1);document.getElementById("Engine").addEventListener("mousedown",
gameModule.makeEngine,!1);document.getElementById("Restart").addEventListener("mousedown",gameModule.restart,!1);gameModule.getCanvas().addEventListener("mousedown",g,!1)},getContent:function(d){return document.getElementById(d)}}}(),gameModule=function(){function m(a,b,c,d){e.beginPath();e.fillStyle="#000000";e.rect(a,b,c,c);e.closePath();e.stroke();e.fillStyle=d?"green":"white";e.fill()}function g(a,b){a>=f&&(a=0);b>=f&&(b=0);0>a&&(a=f-1);0>b&&(b=f-1);return l[a][b]}function d(a,b){a>=f&&(a=0);
b>=f&&(b=0);0>a&&(a=f-1);0>b&&(b=f-1);return{x:a,y:b}}function x(a,b){var c=0;g(a-1,b-1)&&c++;g(a,b-1)&&c++;g(a+1,b-1)&&c++;g(a-1,b)&&c++;g(a+1,b)&&c++;g(a-1,b+1)&&c++;g(a,b+1)&&c++;g(a+1,b+1)&&c++;return c}function y(a){for(var b=0;b<a.length;b++)m(a[b].i*h+1,a[b].j*h+1,h,l[a[b].i][a[b].j])}function b(a,b){l[a][b]=!0;t(a,b);m(a*h+1,b*h+1,h,l[a][b])}function t(a,b){var c;c=d(a,b);k.push(JSON.stringify({i:c.x,j:c.y}));c=d(a-1,b-1);k.push(JSON.stringify({i:c.x,j:c.y}));c=d(a,b-1);k.push(JSON.stringify({i:c.x,
j:c.y}));c=d(a+1,b-1);k.push(JSON.stringify({i:c.x,j:c.y}));c=d(a+1,b);k.push(JSON.stringify({i:c.x,j:c.y}));c=d(a+1,b+1);k.push(JSON.stringify({i:c.x,j:c.y}));c=d(a,b+1);k.push(JSON.stringify({i:c.x,j:c.y}));c=d(a-1,b+1);k.push(JSON.stringify({i:c.x,j:c.y}));c=d(a-1,b);k.push(JSON.stringify({i:c.x,j:c.y}))}function u(){if(n){k=k.getUnique();for(var a=[],b=[],c=0;c<k.length;c++){var d=JSON.parse(k[c]),e=x(d.i,d.j);l[d.i][d.j]?2==e||3==e?b.push({i:d.i,j:d.j,value:!0}):b.push({i:d.i,j:d.j,value:!1}):
3==e?b.push({i:d.i,j:d.j,value:!0}):b.push({i:d.i,j:d.j,value:!1});l[d.i][d.j]!=b[b.length-1].value&&a.push({i:d.i,j:d.j})}k=[];for(c=0;c<b.length;c++)l[b[c].i][b[c].j]=b[c].value,b[c].value&&t(b[c].i,b[c].j);y(a);setTimeout(function(){u()},5)}}var f,p,v,h,e,q,r,l,k,w=!1,n;Array.prototype.getUnique=function(){for(var a={},b=[],c=0,d=this.length;c<d;++c)a.hasOwnProperty(this[c])||(b.push(this[c]),a[this[c]]=1);return b};return{initialize:function(){0==w&&(w=!0,p=document.getElementById("main"),v=0,
e=p.getContext("2d"),e.lineWidth=.5,q=p.width,r=p.height,l=[],k=[],n=!1)},run:function(){n=!0;u()},pause:function(){n=!1},restart:function(){n=!1;f=parseInt(UIModule.getContent("dimension").value);h=q/(f+v);for(var a=0;a<f;a++){l[a]=[];for(var b=0;b<f;b++)l[a][b]=!1}e.clearRect(0,0,q,r);for(a=0;a<f;a++)e.beginPath(),e.moveTo(a*h+1,0),e.lineTo(a*h+1,r),e.stroke(),e.beginPath(),e.moveTo(0,a*h+1),e.lineTo(q,a*h+1),e.stroke()},isRunning:function(){return n},makeAcorn:function(){var a=parseInt(f/2);b(a,
a);b(a+1,a);b(a+1,a-1);b(a+2,a);b(a+2,a+1)},makeGun:function(){var a=parseInt(f/2);b(a-15,a+1);b(a-15,a+2);b(a-14,a+1);b(a-14,a+2);b(a-5,a+1);b(a-5,a+2);b(a-5,a+3);b(a-4,a+4);b(a-4,a);b(a-3,a+5);b(a-2,a+5);b(a-3,a-1);b(a-2,a-1);b(a-1,a+2);b(a+1,a+2);b(a+1,a+1);b(a+1,a+3);b(a+2,a+2);b(a,a);b(a,a+4);b(a+5,a);b(a+5,a-1);b(a+5,a+1);b(a+6,a);b(a+6,a-1);b(a+6,a+1);b(a+7,a+2);b(a+7,a-2);b(a+9,a-2);b(a+9,a-3);b(a+9,a-2);b(a+9,a-3);b(a+9,a+3);b(a+9,a+2);b(a+19,a);b(a+19,a-1);b(a+20,a);b(a+20,a-1)},makeWalker:function(){var a=
parseInt(f/2);b(a,a);b(a+1,a);b(a+1,a+1);b(a+2,a+1);b(a+2,a-1)},makeEngine:function(){var a=parseInt(f/2);b(a-20,a);b(a-19,a);b(a-18,a);b(a-17,a);b(a-16,a);b(a-15,a);b(a-14,a);b(a-13,a);b(a-11,a);b(a-10,a);b(a-9,a);b(a-8,a);b(a-7,a);b(a-3,a);b(a-2,a);b(a-1,a);b(a+6,a);b(a+7,a);b(a+8,a);b(a+9,a);b(a+10,a);b(a+11,a);b(a+12,a);b(a+14,a);b(a+15,a);b(a+16,a);b(a+17,a);b(a+18,a)},getCanvas:function(){return p},drawCell:function(a,b){l[a][b]=l[a][b]?!1:!0;m(a*h+1,b*h+1,h,l[a][b])},getCanvas:function(){return p},
getCellDiameter:function(){return h}}}();window.onload=function(){gameModule.initialize();gameModule.restart();UIModule.initialize()};
